### ISSUE TITLE
Button disappearing from toolbar

### ISSUE THREAD

**Issue by grumpygeek** [wsdfhjxc/crush-those-cookies#4] opened 2016-09-02 04:35 UTC
Now that you've got everything working good, maybe you could look into the vanishing button (=icon) issue.  I know it isn't specific to your extension - it's at least partially due to something in the browser code and it's been occurring for years.  SDC is bad about it too.  At least with CTC it's always found hiding in the Cutomize palette so far (SDC sometimes vanishes completely).  After restart is one time when it happens; there may be others.  If you want to do a special debug version with some special troubleshooting code, I will give that a try.  I couldn't find anything in the Error Console.  And it's happened from different positions and toolbars.  Win8.1 (but I know this same sort of thing happened on XP too.)

Probably not related, but after updating, I have 2 CTC icons in the palette until restart.  Haven't seen that with other extensions.  EDIT: also first two items on context menu are blank (no text) after first dragging to toolbar after update but clears up on restart.

**Comment by wsdfhjxc** [comment] 2016-09-02 12:16
Thanks for pointing that out. From what I've read apparently handling toolbar buttons properly in bootstrapped extensions can be quite troublesome. If I recall correctly even uBlock Origin caused duplications of its own icon inside customization palette under some circumstances. I'll try to repair this.

**Comment by wsdfhjxc** [comment] 2016-09-03 20:28
It seems to be fixed now as I can't reproduce this issue anymore. So, I'll close this for now. Let me know if there are still some problems here.

**Closed by wsdfhjxc** 2016-09-03 20:28 UTC
